# Generated by Django 3.0.7 on 2021-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='level',
            field=models.CharField(choices=[('level2', 'general'), ('level1', 'easy'), ('level3', 'difficult')], max_length=10, verbose_name='题目难度'),
        ),
        migrations.AlterField(
            model_name='fillblankquestion',
            name='level',
            field=models.CharField(choices=[('level2', 'general'), ('level1', 'easy'), ('level3', 'difficult')], max_length=10, verbose_name='题目难度'),
        ),
        migrations.AlterField(
            model_name='judgequestion',
            name='level',
            field=models.CharField(choices=[('level2', 'general'), ('level1', 'easy'), ('level3', 'difficult')], max_length=10, verbose_name='题目难度'),
        ),
    ]
