# Generated by Django 3.0.7 on 2021-01-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_auto_20210118_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='fillblankquestion',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='judgequestion',
            name='subject',
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='题目编号'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='level',
            field=models.CharField(choices=[('level3', 'difficult'), ('level2', 'general'), ('level1', 'easy')], max_length=10, verbose_name='题目难度'),
        ),
        migrations.AlterField(
            model_name='fillblankquestion',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='题目编号'),
        ),
        migrations.AlterField(
            model_name='fillblankquestion',
            name='level',
            field=models.CharField(choices=[('level3', 'difficult'), ('level2', 'general'), ('level1', 'easy')], max_length=10, verbose_name='题目难度'),
        ),
        migrations.AlterField(
            model_name='judgequestion',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='题目编号'),
        ),
        migrations.AlterField(
            model_name='judgequestion',
            name='level',
            field=models.CharField(choices=[('level3', 'difficult'), ('level2', 'general'), ('level1', 'easy')], max_length=10, verbose_name='题目难度'),
        ),
    ]
